services:
  frontend:
    build: ./frontend
    profiles: ["prod"]
    ports:
      - "8080:80"

  frontend-dev:
    build: ./frontend
    profiles: ["dev"]
    command: npm run dev
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    profiles: ["prod"]
    ports:
      - "1337:1337"
    environment:
      HOST: "0.0.0.0"
      NODE_ENV: "production"
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapipassword
    depends_on:
      - db

  backend-dev:
    build: ./backend
    profiles: ["dev"]
    command: npm run develop
    ports:
      - "1337:1337"
    environment:
      HOST: "0.0.0.0"
      NODE_ENV: "development"
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapipassword
    volumes:
      - ./backend/config:/app/config
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapipassword
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data

volumes:
  strapi-data:
